language: php

php:
  - 5.4

env:
  global:
  - secure: fYpFV4xbOKWJ014ILpTbMl1j5PrrDPtiZ+3k1qZJCpz5UUQ0UGIHB8UjNAIAKdQ9aUKU8iG/wNiPrw95Ks57qwwyYyeJUtRe+74pcwZA5IB/BZy/0kFvotnx2udJjUQN4XgteLHodxpOSHEWfr6w7Y5xHXYUSdqqg8jq1fZFbUo=
  - secure: jMKyA20GQoNiOaOXkFDeVFsGKMByebIzEbW6UOXOhHwex2ZQqqDqE7FLokYX4Hz2xN2A/17SENdYdZ9A2dEiV9GWWYYhEyjQPGDYK2LtUGomu877jobBkrNqd2lSbZiIoOddw8XahcNVOFtsKLEvvTk1m9DpRtzK5p56s1i+3H8=

addons:
  sauce_connect: true

before_script:
   - sudo apt-get install apache2 libapache2-mod-fastcgi
   # enable php-fpm
   - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
   - sudo a2enmod rewrite actions fastcgi alias
   - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
   # configure apache virtual hosts
   - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
   - sudo service apache2 restart
  - composer self-update
  - pyrus channel-discover pear.phpunit.de
  - pyrus channel-discover pear.symfony.com
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash

script:
  - composer install
  - vendor/bin/paratest -p 2 -f --phpunit=vendor/bin/phpunit tests/system/saucelabs/WebDriverDemo.php
