language: php

php:
  - 5.3
  - 5.4

env:
  global:
  - secure: fYpFV4xbOKWJ014ILpTbMl1j5PrrDPtiZ+3k1qZJCpz5UUQ0UGIHB8UjNAIAKdQ9aUKU8iG/wNiPrw95Ks57qwwyYyeJUtRe+74pcwZA5IB/BZy/0kFvotnx2udJjUQN4XgteLHodxpOSHEWfr6w7Y5xHXYUSdqqg8jq1fZFbUo=
  - secure: jMKyA20GQoNiOaOXkFDeVFsGKMByebIzEbW6UOXOhHwex2ZQqqDqE7FLokYX4Hz2xN2A/17SENdYdZ9A2dEiV9GWWYYhEyjQPGDYK2LtUGomu877jobBkrNqd2lSbZiIoOddw8XahcNVOFtsKLEvvTk1m9DpRtzK5p56s1i+3H8=

addons:
  sauce_connect: true

before_script:
  - composer self-update
  - pyrus channel-discover pear.phpunit.de
  - pyrus channel-discover pear.symfony.com
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash

script:
  - vendor/bin/paratest -p 2 -f --phpunit=vendor/bin/phpunit tests/system/saucelabs/WebDriverDemo.php
